### ISSUE TITLE
Didn't work at first. Had to edit the file.

### ISSUE THREAD

**Issue by gpaschetto** [2ndkauboy/hello-world#1] opened 2023-09-26 00:05 UTC
I could not change the lyrics file on the plugin settings page. I found that if I removed the call to wp_unslash() it worked fine. I was happy until the last update undid it, so I figured I'd let you know what I experienced. 

UPDATE: Now I feel silly. While it did not work on my dev machine (XAMPP) it works fine on final production server.

**Comment by 2ndkauboy** [comment] 2023-09-26 18:58
@gpaschetto thanks for reporting that issue! But just like you, I was not able to reproduce it locally on my development laptop. So can we close this issue?

**Closed as completed** 2024-07-03 13:02 UTC
